/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.io.*;
//import java.awt.*;
import java.io.*;
import java.util.*;
public class NMapSelect extends javax.swing.JFrame {

    /**
     * Creates new form NMapSelect
     */
    String myIp; //to store the my ip address separately
    String Loc; // to get the path of where to store the exporting folder in client system
    public NMapSelect(String str1,String loc) {
        Loc=loc;        // this is the gateway
       initComponents();
         String [] str=new String[100]; //this is to store each value of the NMapResults separatly
   String temp=new String(); //an intermediate to store strings temperorely and set them in str array if not null
     int i=0;
     //while(i<9){
    // chk[i].setText("abcd");
     //jp.add(chk[i]);
    //// i++;
    // }
     //i=1;
     
     
    try{ BufferedReader br=new BufferedReader(new FileReader(str1));
while((temp=br.readLine())!=null){
    str[i]=temp;//jList1.add(temp, jList1);
    myIp=temp;
   //chk[i].setSelected(true);
   //jp.add(chk[i]);
 
    System.out.println(str[i]);
i++;    
}}
   
catch(IOException e){
} jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = str;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });          
  //JList list=new JList(str);
//JScrollPane jsp=new JScrollPane(list);
//jsp.setLocation(200, 300);
//JPanel p=new JPanel();
//p.setSize(200,200);
//p.setLocation(100, 50);
//p.add(jsp);
//this.setSize(500,500);
//this.add(p);

 this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telnetpass = new javax.swing.JTextField();
        adminpass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Select Computers");

        jList1.setFixedCellHeight(20);
        jList1.setFixedCellWidth(9);
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Access UserName");

        jLabel3.setText("Access Password");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel4.setText("Admin Password");

        telnetpass.setForeground(new java.awt.Color(255, 255, 255));

        adminpass.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telnetpass)
                    .addComponent(adminpass))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telnetpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String str=System.getProperty("user.dir");
 str=str.concat("\\LastLst.txt");
 JOptionPane.showMessageDialog(null,"your ip is "+myIp);

 for(int i=0;i<100;i++){
 //if(jList1.get(i).toString()!=null){}
 
 }
Loc=Loc.replace("(", "{(}");
Loc=Loc.replace(")","{)}");
 
 List<String> myList= jList1.getSelectedValuesList();
 
    try {
        //BufferedWriter buffer = new BufferedWriter(new FileWriter(new File(str),true));
        System.out.println(myList.size());
        for(int i = 0 ; i<myList.size();i++){
            System.out.println(i+ ". "+ myList.get(i).toString());
            try{
                Process ps=Runtime.getRuntime().exec("cmd /c execute.bat "+myList.get(i).toString()+" "+username.getText()+" "+telnetpass.getText()+" "+adminpass.getText()+" "+myIp+" \""+Loc+"\"");
                ps.waitFor();
            }
            
            catch(Exception e){
                
                e.printStackTrace();
                
            }
            
        }
        //buffer.close();

    } catch (Exception ex) {
        //....
    }          
      
    JOptionPane.showMessageDialog(null, "Software Installed Successfully \n thanks for using me as your personal assistant", "EveryThing DOne!",1);
    //System.exit(0);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField telnetpass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
